sudo: false
dist: trusty
language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"

cache:
  bundler: true
bundler_args: --without development
before_install:
  - gem install bundler
  - gem update --system
script:
  - bundle exec rake
